#!/bin/bash
sudo yum update -y

sudo yum install -y httpd httpd-tools mod_ssl

sudo systemctl start httpd

sudo systemctl enable httpd

sudo amazon-linux-extras | grep php

sudo amazon-linux-extras enable php7.4

sudo yum clean metadata

sudo yum install php php-common php-pear -y
sudo yum install -y https://dev.mysql.com/get/mysql80-community-release-el7-1.noarch.rpm
sudo yum install -y mysql-community-client
sudo systemctl start mysqld



